baseURL = 'https://wei-hong.me/'
languageCode = 'zh-cn'
title = '魏洪'
theme = 'paper'
copyright = "©2026 魏洪 | 落子无悔，勇往直前"
[menu]
  [[menu.main]]
    name = "成长"
    pageRef = "/growth"
    weight = 10

  [[menu.main]]
    name = "创造"
    pageRef = "/building"
    weight = 20

  [[menu.main]]
    name = "探索"
    pageRef = "/exploring"
    weight = 30

  [[menu.main]]
    name = "关于"
    pageRef = "/about"
    weight = 100

[taxonomies]
  category = "categories"

[permalinks]
  categories = "/:slug/"